### ISSUE TITLE
Strange Teleport Issue

### ISSUE THREAD

**Issue by jet082** [Shop-kins/TransitionRandomiser#11]
When this is combined with other mods, for example the popular DeathRun mod (https://github.com/Cattlesquat/subnautica) which randomize starting location, ~~since your starting location is not Safe Shallows,~~ the transition randomizer immediately warps you out of your life pod. If you set DeathRun to not randomize starting location, it works fine.

However, it would be nice to be able to run both together. ~~As such, it would be nice to check the biome at the beginning of the game, rather than assuming Safe Shallows.~~

The issue occurs based upon, as far as I can tell, both the initial location of the escape pod and the depth related to the expected location of the escape pod? I took a video to demonstrate this.

The interaction from 1:05 to 1:35 demonstrates the 'depth related to the expected location of the escape pod' and the beginning (starting at 0:15) demonstrates the 'initial location of the escape pod.'

https://user-images.githubusercontent.com/46708077/177112521-f0b14791-2ad2-4224-9785-52f719a74d2a.mp4

**Comment by Shop-kins** [comment]
RESOLVED
